name: armisses_ultra
description: ARMisses Ultra Performance 10Hz
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^11.0.0
  google_fonts: ^6.2.0  # ลดจาก 6.3.3 เป็น 6.2.0 เพื่อให้เข้ากับ SDK 3.3.0 ของคุณครับ
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

# ระบบจัดการไอคอนแบบจบๆ
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
