name: armisses_ultra
description: ARMisses Ultra Performance 10Hz
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^11.0.0      # จัดย่อหน้าตรงเป๊ะแล้ว
  google_fonts: ^6.2.0     # ลดเวอร์ชันเพื่อแก้ Error SDK 3.3.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
